version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: money_conversion_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: 'money-conversion'
        networks:
            - money-conversion

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: money_conversion_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - money-conversion

    # Symfony apache project container
    www:
        build: docker/php
        container_name: money_conversion
        ports:
            - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - money-conversion
        extra_hosts:
            - "money-conversion.local:127.0.0.1"
        environment:
            - VIRTUAL_HOST=money-conversion.local
        #command:  /bin/bash -c "echo '127.0.0.1 money-conversion.local' >> /etc/hosts && composer install && bin/console doctrine:migrations:migrate --no-interaction && apache2-foreground"
        command: /bin/bash -c "echo '127.0.0.1 money-conversion.local' >> /etc/hosts &&
            apache2-foreground" && 
            composer install &&
            bin/console make:migration
            bin/console doctrine:migrations:migrate

networks:
    money-conversion:

volumes:
    db-data:
