somma:
  path: /api/somma
  controller: App\Controller\MoneyConversionController::somma
  methods: [ POST ]

sottrazione:
  path: /api/sottrazione
  controller: App\Controller\MoneyConversionController::sottrazione
  methods: [ POST ]

moltiplicazione:
  path: /api/moltiplicazione
  controller: App\Controller\MoneyConversionController::moltiplicazione
  methods: [ POST ]

divisione:
  path: /api/divisione
  controller: App\Controller\MoneyConversionController::divisione
  methods: [ POST ]

list:
  path: /api/catalogo
  controller: App\Controller\ApiProductController::catalogo
  methods: [ GET ]

prodotto:
  path: /api/prodotto/{id}
  controller: App\Controller\ApiProductController::getProdotto
  methods: [ GET ]

add:
  path: /api/aggiungi-prodotto
  controller: App\Controller\ApiProductController::aggiungiProdotto
  methods: [ GET ]

edit:
  path: /api/edit/{id}
  controller: App\Controller\ApiProductController::editProdotto
  methods: [ GET ]

delete:
  path: /api/delete/{id}
  controller: App\Controller\ApiProductController::delete
  methods: [ GET ]